# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-04 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inventory_details',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inventory_details',
            name='last_count',
        ),
        migrations.RemoveField(
            model_name='inventory_details',
            name='lot',
        ),
        migrations.RemoveField(
            model_name='inventory_details',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='location',
            name='description',
        ),
        migrations.RemoveField(
            model_name='move_log',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='move_log',
            name='updated',
        ),
        migrations.AddField(
            model_name='move_log',
            name='dest_building_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='move_log_dest_building', to='inventory_management_system.Building'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='move_log',
            name='from_building_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='move_log_from_building', to='inventory_management_system.Building'),
            preserve_default=False,
        ),
    ]
