# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-04 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_system', '0002_auto_20170504_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory_details',
            name='quantity',
            field=models.PositiveIntegerField(default='1'),
            preserve_default=False,
        ),
    ]
