# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-11 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_system', '0003_inventory_details_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='move_log',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
