# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-11 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_system', '0004_move_log_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move_log',
            name='dest_building_id',
        ),
        migrations.RemoveField(
            model_name='move_log',
            name='dest_loc_id',
        ),
        migrations.RemoveField(
            model_name='move_log',
            name='from_building_id',
        ),
        migrations.RemoveField(
            model_name='move_log',
            name='from_loc_id',
        ),
        migrations.AddField(
            model_name='move_log',
            name='from_inventory',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='move_log',
            name='to_inventory',
            field=models.CharField(default=None, max_length=15),
            preserve_default=False,
        ),
    ]
