# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-05-24 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management_system', '0006_inventory_details_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory_details',
            name='description',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='lead_time',
            field=models.PositiveIntegerField(verbose_name='Lead Time'),
        ),
    ]
